# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        uses: appleboy/jenkins-action@master
        with:
          url: https://jenkins.maustyle.de
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_SECRET }}
          job: "beat-virus"
